--ejercicio 01
---de 5 tablas usar  la funcion  count(*) ---cata
SELECT * FROM  PERSONA;---LISTAR TODOS LOS DATOS
SELECT NOMBRE , APELLIDO_MATERNO, APELLIDO_PATERNO FROM PERSONA;
SELECT COUNT(*)AS  CANTIDAD_PERSONA FROM PERSONA;


SELECT * FROM persona_documento;
SELECT id_persona,estado,id_persona FROM persona_documento;
SELECT COUNT(*)AS  TIPO_DOCUMENTO FROM persona_documento;

SELECT 
NOMBRE,
APELLIDO_MATERNO AS MATERNO,
APELLIDO_PATERNO AS PATERNO
FROM PERSONA;
SELECT COUNT (*) AS CANTIDAD_PERSONA FROM PERSONA;

SELECT * FROM  tipo_documento;---LISTAR TODOS LOS DATOS
SELECT NOMBRE , sigla, orden FROM tipo_documento;
SELECT COUNT(*)AS  CANTIDAD_DOCUEMNTOS  FROM tipo_documento;


SELECT * FROM  ESTADO_CIVIL;---LISTAR TODOS LOS DATOS
SELECT NOMBRE , sigla FROM estado_civil;
SELECT COUNT(*)AS  CANTIDAD_NOMBRES  FROM ESTADO_CIVIL;

SELECT * FROM  GENERO;---LISTAR TODOS LOS DATOS
SELECT NOMBRE , sigla FROM genero;
SELECT COUNT(*)AS  CANTIDAD_GENEROS  FROM genero;


--EJERCICIO 02

---USO DE LA CLAUSULA WHERE
